# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import threading
import jarvis


class Ui_MainWindow(object):
    def __init__(self):
        self.pushButton = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-20, -110, 1151, 811))
        self.Bg_1.setAutoFillBackground(False)
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("material/Black_Template.jpg"))
        self.Bg_1.setObjectName("Bg_1")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(-120, 90, 721, 501))
        self.Gif_1.setStyleSheet("border-color: rgb(85, 255, 255);")
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("material/Siri.gif"))
        self.Gif_1.setScaledContents(False)
        self.Gif_1.setObjectName("Gif_1")
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(-90, 10, 321, 61))
        self.Bg_2.setText("")
        
        self.Bg_2.setPixmap(QtGui.QPixmap("material/jarvis_logo_intro_dribbble_2.png"))
        self.Bg_2.setScaledContents(False)
        self.Bg_2.setObjectName("Bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(560, 40, 541, 281))
        self.bg_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.bg_3.setText("")
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(570, 50, 521, 261))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("material/Iron_Template_1.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 490, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border:1px solid white;")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 490, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border:1px solid white;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_2.setText(_translate("MainWindow", "Close"))


def jarvis_run():
    # while True:
    jarvis.main()


def run():
    threading.Thread(target=jarvis_run).start()

    def flush(self):
        pass




def startFunc():
    ui.movie = QtGui.QMovie(
        "material/Siri.gif")  # if it doesn't work then give full path

    ui.Gif_1.setMovie(ui.movie)

    ui.movie.start()

    ui.movie_1 = QtGui.QMovie(
        "material/Iron_Template_1.gif")  # if it doesn't work then give full path

    ui.Gif_2.setMovie(ui.movie_1)

    ui.movie_1.start()
    threading.Thread(target=jarvis_run).start()
    # startFunc.start()



def close_1():
    
    exit()



# if __name__ == "__main__":
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
ui.pushButton.clicked.connect(startFunc)
ui.pushButton_2.clicked.connect(close_1)
MainWindow.show()
sys.exit(app.exec_())










